service: factorial-api

framework:
  name: serverless

provider:
  name: aws
  region: ${opt:region, default: us-east-1}
  runtime: nodejs20.x

functions:
  api:
    handler: app.handler
    events:
      - http:
          path: /
          method: GET
    environment:
      AUTHORIZED_USERS: '${file(authorized_users.txt)}'  # Replace with actual users

plugins:
  - serverless-offline